
mybatis:
    mapper-locations: classpath*:mapper/**/*.xml
spring:
    redis:
        host: 192.168.210.52
        port: 10379
        password: NNW@com.205
        database: 0
    datasource:
        url: jdbc:mysql://rm-cn-9lb3bguq9000hzqo.rwlb.rds.aliyuncs.com:3306/test
        username: root
        password: Liao514136@
rocketmq:
    name-server: 192.168.206.219:9876
    producer:
        group: producer-router
server:
    port: 8686