server:
    port: 8989

mq:
    host: 192.168.206.219:9876
    proxy: 192.168.206.219:8081
    topic: TopicTest

mock:
    job: true
    rpa.count: 10

spring:
    redis:
        host: 192.168.210.52
        port: 10379
        password: NNW@com.205
        database: 0
    datasource:
        url: jdbc:mysql://rm-cn-9lb3bguq9000hzqo.rwlb.rds.aliyuncs.com:3306/test
        username: root
        password: Liao514136@

mybatis:
    mapper-locations: classpath:/mapper/**/*.xml
