
rocketmq:
    name-server: 192.168.206.219:9876
    producer:
        group: producer-worker
#logging:
#    config: classpath:log4j2.xml

worker:
    role: slave
    dataDir: C:\Users\Administrator\slave
    groupId: wg-1
    workerId: wk-slave
server:
    port: 8081
