rocketmq:
    name-server: 192.168.206.219:9876
logging:
    config: classpath:log4j2.xml
spring:
    mvc:
        async:
            request-timeout: 1
server:
    tomcat:
        connection-timeout: 1